welcome-message: true

connectors:
  websocket:
    type: websocket

skills:
  ci:
    path: /home/opsdroid/.config/opsdroid/skills/ci
  logs:
    path: /home/opsdroid/.config/opsdroid/skills/logs
  explain:
    path: /home/opsdroid/.config/opsdroid/skills/explain